language: android
jdk: oraclejdk8
sudo: false # false for Container-Based Infrastructure, required for Sudo-enabled Infrastructure
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml"

branches:
  only:
    - master

notifications:
  slack: tpft:uDf3mAwrYHFj6aNYw4ijeoDH
  email: false

env:
 global:
   - ANDROID_API=26 # targetSdkVersion in build.graddle
   - EMULATOR_API=18 # The emulator will run this Sdk (must be 16 or newer)
   - ANDROID_BUILD_TOOLS=26.0.2 # buildToolsVersion in build.gradle

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API

before_install:
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew build connectedCheck
