language: android
jdk: oraclejdk8
sudo: false # false for Container-Based Infrastructure, required for Sudo-enabled Infrastructure

branches:
  only:
    - master

notifications:
  slack: tpft:uDf3mAwrYHFj6aNYw4ijeoDH
  email: false

env:
 global:
   - ANDROID_API=26 # targetSdkVersion in build.graddle
   - ANDROID_BUILD_TOOLS=26.0.2 # buildToolsVersion in build.gradle

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API

before_install:
  - chmod +x gradlew

after_script: "cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml"
