language: android
jdk: oraclejdk8
sudo: required # false for Container-Based Infrastructure, required for Sudo-enabled Infrastructure
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

branches:
  only:
    - master

notifications:
  slack: tpft:uDf3mAwrYHFj6aNYw4ijeoDH
  email: false

language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.2
    - android-26

before_install:
  - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
